#nullable enable
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;

#pragma warning disable RS2008

namespace Nebula.Generator;

/// <summary>
/// Source generator that creates InvokeNetFunctionByName overrides for classes with [NetFunction] methods.
/// This enables direct C# method dispatch without Variant conversion or Godot boundary crossing.
/// </summary>
[Generator]
public class NetFunctionGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var functions = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                "Nebula.NetFunction",
                predicate: (node, _) => node is MethodDeclarationSyntax,
                transform: (ctx, _) => GetFunctionInfo(ctx))
            .Where(f => f is not null)
            .Collect();

        context.RegisterSourceOutput(functions, GenerateSource!);
    }

    private static FunctionInfo? GetFunctionInfo(GeneratorAttributeSyntaxContext context)
    {
        var methodSymbol = (IMethodSymbol)context.TargetSymbol;
        var containingType = methodSymbol.ContainingType;

        var parameters = new List<ParameterData>();
        foreach (var param in methodSymbol.Parameters)
        {
            var isEnum = param.Type.TypeKind == TypeKind.Enum;
            string? enumUnderlyingType = null;
            if (isEnum && param.Type is INamedTypeSymbol enumType)
            {
                enumUnderlyingType = enumType.EnumUnderlyingType?.ToDisplayString();
            }

            parameters.Add(new ParameterData(
                param.Name,
                param.Type.ToDisplayString(),
                param.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat),
                param.Type.IsValueType,
                isEnum));
        }

        // Read [NetFunction(Source = ...)] to decide eligibility for the peer-targeted overload.
        // Same convention as the protocol builder's TypeAnalyzer: Client=1, Server=2, All=3 (default).
        int source = 3;
        foreach (var attr in context.Attributes)
        {
            foreach (var named in attr.NamedArguments)
            {
                if (named.Key == "Source" && named.Value.Value != null)
                {
                    source = System.Convert.ToInt32(named.Value.Value);
                }
            }
        }

        return new FunctionInfo(
            methodSymbol.Name,
            parameters,
            containingType.Name,
            containingType.ContainingNamespace.IsGlobalNamespace
                ? null
                : containingType.ContainingNamespace.ToDisplayString(),
            GetBaseClassName(containingType),
            source);
    }

    private static string? GetBaseClassName(INamedTypeSymbol type)
    {
        var baseType = type.BaseType;
        while (baseType != null)
        {
            var name = baseType.Name;
            if (name == "NetNode3D" || name == "NetNode2D" || name == "NetNode")
            {
                return name;
            }
            baseType = baseType.BaseType;
        }
        return null;
    }

    private static void GenerateSource(
        SourceProductionContext context,
        ImmutableArray<FunctionInfo?> functions)
    {
        var grouped = functions
            .Where(f => f is not null)
            .GroupBy(f => (f!.Namespace, f.ClassName));

        foreach (var group in grouped)
        {
            var (ns, className) = group.Key;
            var funcList = group.ToList();
            
            if (funcList.Count == 0) continue;
            
            var baseClass = funcList.First()?.BaseClassName;
            if (baseClass == null) continue;

            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated />");
            sb.AppendLine("#pragma warning disable CS0109");
            sb.AppendLine();

            if (ns is not null)
                sb.AppendLine($"namespace {ns};");

            sb.AppendLine($"partial class {className}");
            sb.AppendLine("{");
            
            sb.AppendLine("    /// <summary>");
            sb.AppendLine("    /// Invokes a network function by name with PropertyCache arguments.");
            sb.AppendLine("    /// Auto-generated by Nebula for direct C# dispatch without Variant conversion.");
            sb.AppendLine("    /// </summary>");
            sb.AppendLine("    internal override void InvokeNetFunctionByName(string funcName, Nebula.PropertyCache[] args)");
            sb.AppendLine("    {");
            sb.AppendLine("        switch (funcName)");
            sb.AppendLine("        {");

            foreach (var func in funcList)
            {
                sb.AppendLine($"            case \"{func!.FunctionName}\":");
                
                var argExprs = new List<string>();
                for (int i = 0; i < func.Parameters.Count; i++)
                {
                    var param = func.Parameters[i];
                    var cacheReadExpr = GeneratorUtils.GetCacheReadExpression(
                        param.TypeName,
                        param.IsEnum,
                        param.IsValueType,
                        $"args[{i}]");
                    argExprs.Add(cacheReadExpr);
                }
                
                var argsString = string.Join(", ", argExprs);
                sb.AppendLine($"                {func.FunctionName}({argsString});");
                sb.AppendLine("                break;");
            }

            sb.AppendLine("            default:");
            sb.AppendLine("                base.InvokeNetFunctionByName(funcName, args);");
            sb.AppendLine("                break;");
            sb.AppendLine("        }");
            sb.AppendLine("    }");

            // Peer-targeted overloads. Server-only variants that deliver the RPC to a chosen subset of
            // peers instead of every interested peer. Only emitted for functions the server may
            // initiate (Source includes Server = bit 2); Source=Client functions run on the server and
            // can't be server-sent, so a targeted variant would send nothing.
            const int ServerBit = 2;
            foreach (var func in funcList)
            {
                if (func is null || (func.Source & ServerBit) == 0) continue;

                var sigBuilder = new StringBuilder("global::Nebula.UUID[] peers");
                var callArgs = new StringBuilder();
                for (int i = 0; i < func.Parameters.Count; i++)
                {
                    var p = func.Parameters[i];
                    sigBuilder.Append($", {p.QualifiedTypeName} {p.Name}");
                    if (i > 0) callArgs.Append(", ");
                    callArgs.Append(p.Name);
                }

                sb.AppendLine();
                sb.AppendLine("    /// <summary>");
                sb.AppendLine($"    /// Server-only peer-targeted send of {func.FunctionName}: delivers the RPC to specified <paramref name=\"peers\"/> only,");
                sb.AppendLine("    /// instead of broadcasting to every interested peer. Specified peers must have object interest or the call is skipped on them.");
                sb.AppendLine("    /// ExecuteOnCaller is unchanged (the method still runs on the server).");
                sb.AppendLine("    /// runs on the server). Auto-generated by Nebula.");
                sb.AppendLine("    /// </summary>");
                sb.AppendLine($"    public void {func.FunctionName}({sigBuilder})");
                sb.AppendLine("    {");
                sb.AppendLine("        if (!Network.IsServer)");
                sb.AppendLine($"            throw new global::System.InvalidOperationException(\"{func.FunctionName}(global::Nebula.UUID[], ...) is a server-only peer-targeted variant and cannot be called on a client.\");");
                sb.AppendLine("        global::Nebula.NetFunctionCall.TargetPeers = peers;");
                sb.AppendLine("        try");
                sb.AppendLine("        {");
                sb.AppendLine($"            {func.FunctionName}({callArgs});");
                sb.AppendLine("        }");
                sb.AppendLine("        finally");
                sb.AppendLine("        {");
                sb.AppendLine("            global::Nebula.NetFunctionCall.TargetPeers = null;");
                sb.AppendLine("        }");
                sb.AppendLine("    }");
            }

            sb.AppendLine("}");

            context.AddSource($"{className}.NetFunctions.g.cs", sb.ToString());
        }
    }

    private record FunctionInfo(
        string FunctionName,
        List<ParameterData> Parameters,
        string ClassName,
        string? Namespace,
        string? BaseClassName,
        int Source);

    private record ParameterData(
        string Name,
        string TypeName,
        string QualifiedTypeName,
        bool IsValueType,
        bool IsEnum);
}
